### PR TITLE
Static search

### PR DESCRIPTION
**Pull request by ghtmtt**
Sticky search box :)

[vokoscreenNG-2022-12-16_17-33-41.webm](https://user-images.githubusercontent.com/2884884/208145555-53a63712-5d84-403d-8727-cfb718284a7a.webm)

### CODE REVIEW

**Comment by ghtmtt** [comment]
almost forgot. Full credits to @Mind84

**Comment by DelazJ** [comment]
Looks great to me. +1

**Comment by andreasneumann** [comment]
Very nice! That's the best we can do.

**Comment by 3nids** [comment]
Nice!
@ghtmtt i just gave you access to the repo so you can push upstream for the pull requests

**Comment by ghtmtt** [comment]
@3nids thanks! I'll still play with the fork so I can safely test the changes there.

**Pull request merged**
