### PR TITLE
Use a wider width for pyQGIS documentation for text and tables

### LINKED ISSUE #36: Problem showing tables at docs.
Hi, i have been studing PyQgis docs and i found something.
Some descriptions are bigger than cell, that needs a scroll to see all description.

image

Maybe, can it set at CSS or html from the theme to make a line break.

I have tested in chrome and firefox.

### PR DESCRIPTION
**Pull request by DelazJ**
supersedes #88
Fixes #36

### CODE REVIEW

**Comment by 3nids** [comment]
@DelazJ can we merge this?

**Comment by DelazJ** [comment]
No, It doesn't work as expected (frame has still the same width). I fail to find how to reference the css file in the conf file. And I suspect (I may be wrong) this is what @ghtmtt is trying to fix (or at least it can rely on his attempt and update this accordingly)

**Comment by ghtmtt** [comment]
@DelazJ it seems that what @3nids suggested, adding the following to `build-docs.sh`, is working:

`cp -r _static api/${QGIS_VERSION}/_static`

**Comment by 3nids** [comment]
result can be seen here https://qgis.org/pyqgis/master_PR89/

**Comment by DelazJ** [comment]
So... according to that build, the PR fixed nothing 😢 . I couldn't build locally (something about 'qgis' not found) but considering that this PR includes @ghtmtt changes that successfully added (locally) a scrollbar and I can't see that scrollbar in this artifact, I wonder if there is not something wrong with the action output...

**Comment by ghtmtt** [comment]
@DelazJ this is my command:

`./build-docs.sh -c QgsVectorLayer -qgis-build-dir /home/matteo/dev/qgis-master/`

I'm within the `pyqgis/script` folder and `/home/matteo/dev/qgis-master/` is the path of my cloned QGIS repository. Thanks to @3nids suggestions, the `-c QgsVectorLayer` (or whatever class you want) is limiting the build to just that class and seeps up a lot the build.

**Comment by DelazJ** [comment]
Thanks @ghtmtt. I was unsure of the path so tried with the repo folder, the build folder and the output folder within it. Retried now with just the repo and still getting the `ModuleNotFoundError: no module named 'qgis'`.
If ever you have a moment and want to cherry-pick my commit and test, it would be very great. TIA.

**Comment by ghtmtt** [comment]
seems perfect!

image

**Comment by DelazJ** [comment]
GREAT!!! Thanks @ghtmtt 
@3nids if OK with you...

**Comment by ghtmtt** [comment]
just for info and not related to this OR. I was trying, without any success, to add a `Go to top` button always in the sidebar to easily to back to the search bar... Maybe you have some suggestion or link where I can have a look at ;)

**Comment by DelazJ** [comment]
@ghtmtt no idea right now. This looks related to #103.

**Comment by ghtmtt** [comment]
I totally missed that issue. I think jumping with a button up would be the most elegant solution.

**Comment by DelazJ** [comment]
> I totally missed that issue.

Normal. It was reported after your question.

**Comment by ghtmtt** [comment]
@DelazJ I didn't look at the date. Strange coincidence :D

**Pull request merged**
