### PR TITLE
Display full list of versions in bottom menu

### PR DESCRIPTION
**Pull request by DelazJ**
I assume this script is meant to provide uniform list of versions in the bottom menu, if run. We currently have many lists

### CODE REVIEW

**Comment by ghtmtt** [comment]
@DelazJ is this still valid?

**Comment by DelazJ** [comment]
It depends...
Do we want to still display full list of old docs in the bottom menu or are we putting older versions in an archive page? Refs #104

**Comment by ghtmtt** [comment]
Is this the script that generates this page https://qgis.org/pyqgis/?

**Comment by DelazJ** [comment]
No, that is the index page at https://github.com/qgis/pyqgis/blob/gh-pages/index.html (if I'm not mistaken, manually updated).

When 3.20 docs were released, there was no 3.28 link (obvious!), so it could miss in the bottom menu. The script here would help to add 3.28 there and display the same list of versions in the bottom menu for every version. Assuming I understand the script😄 . this helps to quickly switch between recent and old versions from within the bottom menu and check potential display issues (in my case).

**Comment by ghtmtt** [comment]
OK, LGTM. Thanks!

**Pull request merged**
