### PR TITLE
Remove sphinxcontrib-jquery from dockerfile as already included in conf file

### LINKED ISSUE #109: Search bar is not working
For more recent versions of the PyQGIS API, the search bar is not working. Keeps spinning but does not retrieve any results.

### PR DESCRIPTION
**Pull request by DelazJ**
**Sorry in advance for the noise**
I'm hereby trying to find what parts of #111 fixes #109 so that the changes to the repo are kept as minimalist as possible

### CODE REVIEW

**Comment by DelazJ** [comment]
Afaics, search and bottom menu still work correctly with this PR (https://qgis.org/pyqgis/master_PR114/search.html?q=vectortile&check_keywords=yes&area=default) so should be safe to merge.
@3nids @ghtmtt ?

**Comment by ghtmtt** [comment]
+1 for me

**Comment by DelazJ** [comment]
Today's build already failed because of the oversized GH page. We need to reduce it before anything, and unless I overlooked something, I don't think it is something anyone can do...

**Comment by 3nids** [comment]
I will take care of this.

**Comment by 3nids** [comment]
one question related is the interest about publishing all the version of the API since 3.0.
We could stick to master, pr and ltr?

**Comment by SrNetoChan** [comment]
Maybe keep the previous LTR as well? Like for instance now, keeping 3.22 API since many people will take some time to move to 3.28.

**Pull request merged**
